import { GreetingDefinition } from '../types';

// Time-based greetings (morning, afternoon, evening, late night) with and without names
export const generalGreetings: GreetingDefinition[] = [
  // === MORNING GREETINGS WITH NAME ===
  {
    text: ({ name }) => `Good morning, ${name}`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: ({ name }) => `Morning, ${name}`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: ({ name }) => `Welcome back, ${name}`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: ({ name }) => `Hey there, ${name}`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: ({ name }) => `Rise and shine, ${name}!`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: ({ name }) => `${name} has entered the chat`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: ({ name }) => `Look who's up early, ${name}`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: ({ name }) => `Wakey wakey, ${name}`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: ({ name }) => `The legend ${name} returns`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: ({ name }) => `${name}, let's make today count`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: ({ name }) => `Bright and early, ${name}!`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: ({ name }) => `Fresh start, ${name}`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: ({ name }) => `${name} graces us with their presence`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: ({ name }) => `What's good, ${name}?`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: ({ name }) => `${name}, you're glowing today`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: ({ name }) => `Top of the morning, ${name}`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: ({ name }) => `${name}, ready to conquer?`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: ({ name }) => `Good to see you, ${name}`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: ({ name }) => `${name}'s morning has arrived`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: ({ name }) => `Sunrise and ${name}`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: ({ name }) => `${name}, you're up!`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: ({ name }) => `Early bird ${name}`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: ({ name }) => `${name} starts the day right`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: ({ name }) => `Morning sunshine, ${name}`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: ({ name }) => `${name}, let's do this`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: ({ name }) => `Another day, another ${name}`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: ({ name }) => `${name} bringing morning energy`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: ({ name }) => `Well well, ${name}`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: ({ name }) => `${name}, coffee first?`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: ({ name }) => `Today's main character: ${name}`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: ({ name }) => `${name}, new day, new you`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: ({ name }) => `Blessed to see ${name} this morning`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: ({ name }) => `${name} has arrived fashionably early`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: ({ name }) => `Morning champion ${name}`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: ({ name }) => `${name}, crushing it already?`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: ({ name }) => `Oh look, it's ${name}!`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: ({ name }) => `${name}, the early bird!`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: ({ name }) => `Goooood morning ${name}!`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: ({ name }) => `${name}, coffee's ready`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: ({ name }) => `Sunrise and ${name}, perfect combo`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: ({ name }) => `${name} chose to be great today`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: ({ name }) => `There's ${name}!`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: ({ name }) => `${name}, you beautiful human`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: ({ name }) => `Morning vibes with ${name}`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: ({ name }) => `${name}, destroyer of snooze buttons`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },

  // === MORNING GREETINGS WITHOUT NAME ===
  {
    text: 'Good morning',
    mood: 'casual',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: 'Morning',
    mood: 'casual',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: 'Coffee time?',
    mood: 'playful',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: 'Rise and shine!',
    mood: 'playful',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: 'Fresh start',
    mood: 'casual',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: 'Welcome back',
    mood: 'casual',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: 'Hey there',
    mood: 'casual',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: 'Wakey wakey',
    mood: 'playful',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: 'Up bright and early',
    mood: 'casual',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: 'New day, new possibilities',
    mood: 'casual',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: "Let's make it count",
    mood: 'casual',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: 'Morning energy ⚡',
    mood: 'playful',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: 'Sunrise vibes',
    mood: 'playful',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: 'Ready for today?',
    mood: 'casual',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: 'Early bird gets the worm',
    mood: 'playful',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: 'Top of the morning!',
    mood: 'playful',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: 'The day awaits',
    mood: 'casual',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: 'Morning glory',
    mood: 'playful',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: 'Dawn patrol',
    mood: 'playful',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: 'Breakfast energy',
    mood: 'casual',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: 'Here we go again',
    mood: 'playful',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: 'A.M. vibes',
    mood: 'casual',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: 'Carpe diem',
    mood: 'casual',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: 'Morning mood activated',
    mood: 'playful',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: "Sun's up",
    mood: 'casual',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: 'Another beautiful day',
    mood: 'casual',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: 'Morning magic',
    mood: 'playful',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },
  {
    text: 'Wake up and win',
    mood: 'playful',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 12,
  },

  // === AFTERNOON GREETINGS WITH NAME ===
  {
    text: ({ name }) => `Good afternoon, ${name}`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 12 && hour < 18,
  },
  {
    text: ({ name }) => `Afternoon, ${name}`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 12 && hour < 18,
  },
  {
    text: ({ name }) => `Back at it, ${name}?`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 12 && hour < 18,
  },
  {
    text: ({ name }) => `${name} returns`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 12 && hour < 18,
  },
  {
    text: ({ name }) => `Powering through, ${name}`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 12 && hour < 18,
  },
  {
    text: ({ name }) => `Post-lunch ${name}`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 12 && hour < 18,
  },
  {
    text: ({ name }) => `${name}'s back in action`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 12 && hour < 18,
  },
  {
    text: ({ name }) => `Keeping the momentum, ${name}`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 12 && hour < 18,
  },
  {
    text: ({ name }) => `${name}, second wind time`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 12 && hour < 18,
  },
  {
    text: ({ name }) => `Hello again, ${name}`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 12 && hour < 18,
  },
  {
    text: ({ name }) => `${name} in full swing`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 12 && hour < 18,
  },
  {
    text: ({ name }) => `Midday ${name}`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 12 && hour < 18,
  },
  {
    text: ({ name }) => `${name}, still going strong`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 12 && hour < 18,
  },
  {
    text: ({ name }) => `Afternoon energy from ${name}`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 12 && hour < 18,
  },
  {
    text: ({ name }) => `${name}, what's the vibe?`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 12 && hour < 18,
  },
  {
    text: ({ name }) => `Peak hours with ${name}`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 12 && hour < 18,
  },
  {
    text: ({ name }) => `${name} in the zone`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 12 && hour < 18,
  },
  {
    text: ({ name }) => `Catching ${name} in the afternoon`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 12 && hour < 18,
  },
  {
    text: ({ name }) => `${name}, round two`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 12 && hour < 18,
  },
  {
    text: ({ name }) => `Afternoon ${name} hits different`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 12 && hour < 18,
  },
  {
    text: ({ name }) => `${name}, productive afternoon?`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 12 && hour < 18,
  },
  {
    text: ({ name }) => `Recharged ${name}`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 12 && hour < 18,
  },
  {
    text: ({ name }) => `${name} keeping it moving`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 12 && hour < 18,
  },
  {
    text: ({ name }) => `Sunlight and ${name}`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 12 && hour < 18,
  },
  {
    text: ({ name }) => `Hey ${name}, halfway there!`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 12 && hour < 18,
  },
  {
    text: ({ name }) => `${name}, the afternoon warrior`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 12 && hour < 18,
  },
  {
    text: ({ name }) => `Yo ${name}!`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 12 && hour < 18,
  },
  {
    text: ({ name }) => `${name} sliding into the afternoon`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 12 && hour < 18,
  },
  {
    text: ({ name }) => `${name}, golden hour approaching`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 12 && hour < 18,
  },
  {
    text: ({ name }) => `Afternoon champion ${name}`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 12 && hour < 18,
  },
  {
    text: ({ name }) => `${name}, crushing the PM shift`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 12 && hour < 18,
  },
  {
    text: ({ name }) => `Plot twist: it's ${name}`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 12 && hour < 18,
  },

  // === AFTERNOON GREETINGS WITHOUT NAME ===
  {
    text: 'Good afternoon',
    mood: 'casual',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 12 && hour < 18,
  },
  {
    text: 'Afternoon',
    mood: 'casual',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 12 && hour < 18,
  },
  {
    text: 'Back at it!',
    mood: 'playful',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 12 && hour < 18,
  },
  {
    text: 'Powering through',
    mood: 'casual',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 12 && hour < 18,
  },
  {
    text: 'Post-lunch vibes',
    mood: 'playful',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 12 && hour < 18,
  },
  {
    text: 'Afternoon energy',
    mood: 'casual',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 12 && hour < 18,
  },
  {
    text: 'Keeping the flow',
    mood: 'casual',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 12 && hour < 18,
  },
  {
    text: 'Second wind',
    mood: 'casual',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 12 && hour < 18,
  },
  {
    text: 'Hello again',
    mood: 'casual',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 12 && hour < 18,
  },
  {
    text: 'Welcome back',
    mood: 'casual',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 12 && hour < 18,
  },
  {
    text: 'Midday momentum',
    mood: 'casual',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 12 && hour < 18,
  },

  // === EVENING GREETINGS WITH NAME ===
  {
    text: ({ name }) => `Good evening, ${name}`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 18 && hour < 24,
  },
  {
    text: ({ name }) => `Evening, ${name}`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 18 && hour < 24,
  },
  {
    text: ({ name }) => `Golden hour, ${name}`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 18 && hour < 24,
  },
  {
    text: ({ name }) => `Sunset session, ${name}`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 18 && hour < 24,
  },
  {
    text: ({ name }) => `${name} as the day winds down`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 18 && hour < 24,
  },
  {
    text: ({ name }) => `Evening vibes with ${name}`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 18 && hour < 24,
  },
  {
    text: ({ name }) => `${name}, winding down?`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 18 && hour < 24,
  },
  {
    text: ({ name }) => `Twilight ${name}`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 18 && hour < 24,
  },
  {
    text: ({ name }) => `${name} in the evening glow`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 18 && hour < 24,
  },
  {
    text: ({ name }) => `Still going strong, ${name}`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 18 && hour < 24,
  },
  {
    text: ({ name }) => `${name} after hours`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 18 && hour < 24,
  },
  {
    text: ({ name }) => `Nightfall with ${name}`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 18 && hour < 24,
  },
  {
    text: ({ name }) => `${name}, stars are coming out`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 18 && hour < 24,
  },
  {
    text: ({ name }) => `Prime time ${name}`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 18 && hour < 24,
  },
  {
    text: ({ name }) => `${name}, ready to unwind?`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 18 && hour < 24,
  },
  {
    text: ({ name }) => `Dusk and ${name}`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 18 && hour < 24,
  },
  {
    text: ({ name }) => `${name}, moonrise incoming`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 18 && hour < 24,
  },
  {
    text: ({ name }) => `Evening ${name} energy`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 18 && hour < 24,
  },
  {
    text: ({ name }) => `${name}, calling it a day?`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 18 && hour < 24,
  },
  {
    text: ({ name }) => `Cozy evening, ${name}`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 18 && hour < 24,
  },
  {
    text: ({ name }) => `${name} as darkness falls`,
    mood: 'mysterious',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 18 && hour < 24,
  },
  {
    text: ({ name }) => `Magic hour with ${name}`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 18 && hour < 24,
  },
  {
    text: ({ name }) => `${name}, night shifts`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 18 && hour < 24,
  },
  {
    text: ({ name }) => `Evening ${name}, looking good`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 18 && hour < 24,
  },
  {
    text: ({ name }) => `${name}, sunset vibes`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 18 && hour < 24,
  },
  {
    text: ({ name }) => `The night belongs to ${name}`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 18 && hour < 24,
  },
  {
    text: ({ name }) => `${name}, starlight edition`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 18 && hour < 24,
  },
  {
    text: ({ name }) => `Moonlit ${name}`,
    mood: 'mysterious',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 18 && hour < 24,
  },
  {
    text: ({ name }) => `Evening legend ${name}`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 18 && hour < 24,
  },
  {
    text: ({ name }) => `${name}, after dark mode activated`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 18 && hour < 24,
  },
  {
    text: ({ name }) => `Stars out, ${name}'s out`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 18 && hour < 24,
  },

  // === EVENING GREETINGS WITHOUT NAME ===
  {
    text: 'Good evening',
    mood: 'casual',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 18 && hour < 24,
  },
  {
    text: 'Evening',
    mood: 'casual',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 18 && hour < 24,
  },
  {
    text: 'Golden hour',
    mood: 'playful',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 18 && hour < 24,
  },
  {
    text: 'Sunset session',
    mood: 'playful',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 18 && hour < 24,
  },
  {
    text: 'Winding down',
    mood: 'casual',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 18 && hour < 24,
  },
  {
    text: 'Evening vibes',
    mood: 'casual',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 18 && hour < 24,
  },
  {
    text: 'Twilight time',
    mood: 'playful',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 18 && hour < 24,
  },
  {
    text: 'Still going strong',
    mood: 'casual',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 18 && hour < 24,
  },
  {
    text: 'After hours',
    mood: 'playful',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 18 && hour < 24,
  },
  {
    text: 'Evening energy',
    mood: 'casual',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 18 && hour < 24,
  },
  {
    text: 'Night is young',
    mood: 'playful',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 18 && hour < 24,
  },

  // === LATE NIGHT GREETINGS WITH NAME ===
  {
    text: ({ name }) => `Burning the midnight oil, ${name}?`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 0 && hour < 5,
  },
  {
    text: ({ name }) => `Night owl ${name}`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 0 && hour < 5,
  },
  {
    text: ({ name }) => `${name} in the witching hours`,
    mood: 'mysterious',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 0 && hour < 5,
  },
  {
    text: ({ name }) => `Can't sleep, ${name}?`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 0 && hour < 5,
  },
  {
    text: ({ name }) => `${name}'s late night session`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 0 && hour < 5,
  },
  {
    text: ({ name }) => `Vampire hours, ${name}`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 0 && hour < 5,
  },
  {
    text: ({ name }) => `3am ${name} hits different`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 0 && hour < 5,
  },
  {
    text: ({ name }) => `${name} when the world sleeps`,
    mood: 'mysterious',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 0 && hour < 5,
  },
  {
    text: ({ name }) => `Midnight ${name}`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 0 && hour < 5,
  },
  {
    text: ({ name }) => `${name}'s graveyard shift`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 0 && hour < 5,
  },
  {
    text: ({ name }) => `Creatures of the night, ${name}?`,
    mood: 'mysterious',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 0 && hour < 5,
  },
  {
    text: ({ name }) => `${name} in the dark hours`,
    mood: 'mysterious',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 0 && hour < 5,
  },
  {
    text: ({ name }) => `Insomnia club president: ${name}`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 0 && hour < 5,
  },
  {
    text: ({ name }) => `${name}, sleep is for the weak?`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 0 && hour < 5,
  },
  {
    text: ({ name }) => `Night mode ${name}`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 0 && hour < 5,
  },
  {
    text: ({ name }) => `${name} under the stars`,
    mood: 'mysterious',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 0 && hour < 5,
  },
  {
    text: ({ name }) => `Midnight oil expert: ${name}`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 0 && hour < 5,
  },
  {
    text: ({ name }) => `${name}, the night is yours`,
    mood: 'mysterious',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 0 && hour < 5,
  },
  {
    text: ({ name }) => `Nocturnal ${name}`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 0 && hour < 5,
  },
  {
    text: ({ name }) => `${name} vibing at ungodly hours`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 0 && hour < 5,
  },
  {
    text: ({ name }) => `Dark mode ${name}`,
    mood: 'mysterious',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 0 && hour < 5,
  },
  {
    text: ({ name }) => `${name}, tomorrow's problem?`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 0 && hour < 5,
  },
  {
    text: ({ name }) => `${name}, vampire hours`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 0 && hour < 5,
  },
  {
    text: ({ name }) => `3AM ${name} different`,
    mood: 'mysterious',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 0 && hour < 5,
  },
  {
    text: ({ name }) => `The witching hour welcomes ${name}`,
    mood: 'mysterious',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 0 && hour < 5,
  },
  {
    text: ({ name }) => `${name}, sleep is for the weak`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 0 && hour < 5,
  },
  {
    text: ({ name }) => `Fellow insomniac ${name}`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 0 && hour < 5,
  },
  {
    text: ({ name }) => `${name}, the midnight oil burns bright`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 0 && hour < 5,
  },
  {
    text: ({ name }) => `Creature of the night: ${name}`,
    mood: 'mysterious',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 0 && hour < 5,
  },
  {
    text: ({ name }) => `${name}, certified night shifter`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 0 && hour < 5,
  },

  // === LATE NIGHT GREETINGS WITHOUT NAME ===
  {
    text: 'Late night vibes',
    mood: 'casual',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 0 && hour < 5,
  },
  {
    text: 'Hello, night owl',
    mood: 'playful',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 0 && hour < 5,
  },
  {
    text: 'Burning midnight oil',
    mood: 'playful',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 0 && hour < 5,
  },
  {
    text: 'Witching hours',
    mood: 'mysterious',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 0 && hour < 5,
  },
  {
    text: "Can't sleep?",
    mood: 'casual',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 0 && hour < 5,
  },
  {
    text: 'Vampire hours',
    mood: 'playful',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 0 && hour < 5,
  },
  {
    text: '3am hits different',
    mood: 'playful',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 0 && hour < 5,
  },
  {
    text: 'The world sleeps',
    mood: 'mysterious',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 0 && hour < 5,
  },
  {
    text: 'Midnight session',
    mood: 'casual',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 0 && hour < 5,
  },
  {
    text: 'Graveyard shift',
    mood: 'playful',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 0 && hour < 5,
  },
  {
    text: 'Moon vibes',
    mood: 'mysterious',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 0 && hour < 5,
  },
  {
    text: 'Silent hours',
    mood: 'mysterious',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 0 && hour < 5,
  },

  // === TIME-SPECIFIC GREETINGS (with more granular time periods) ===
  // Early Morning (5-8am)
  {
    text: 'Early bird special',
    mood: 'playful',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 8,
  },
  {
    text: 'Crack of dawn energy',
    mood: 'casual',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 8,
  },
  {
    text: ({ name }) => `${name}, up with the sun`,
    mood: 'playful',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 5 && hour < 8,
  },

  // Mid Morning (8-12am)
  {
    text: 'Mid-morning flow',
    mood: 'casual',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 8 && hour < 12,
  },
  {
    text: 'Getting into the groove',
    mood: 'casual',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 8 && hour < 12,
  },
  {
    text: ({ name }) => `${name}, morning momentum`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 8 && hour < 12,
  },

  // Noon (11am-2pm)
  {
    text: 'High noon',
    mood: 'casual',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 11 && hour < 14,
  },
  {
    text: 'Midday power hour',
    mood: 'playful',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 11 && hour < 14,
  },
  {
    text: ({ name }) => `${name}, lunch vibes?`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 11 && hour < 14,
  },

  // Late Afternoon (3-6pm)
  {
    text: 'Golden hour approaching',
    mood: 'casual',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 15 && hour < 18,
  },
  {
    text: 'Late afternoon energy',
    mood: 'casual',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 15 && hour < 18,
  },
  {
    text: ({ name }) => `${name}, almost evening`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 15 && hour < 18,
  },

  // Early Evening (6-9pm)
  {
    text: 'Early evening calm',
    mood: 'casual',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 18 && hour < 21,
  },
  {
    text: 'Dinner time vibes',
    mood: 'casual',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && hour >= 18 && hour < 21,
  },
  {
    text: ({ name }) => `${name}, early night`,
    mood: 'casual',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && hour >= 18 && hour < 21,
  },

  // Midnight (11pm-2am)
  {
    text: 'Midnight special',
    mood: 'mysterious',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && (hour >= 23 || hour < 2),
  },
  {
    text: 'Witching hour active',
    mood: 'mysterious',
    static: { language: 'en', workMode: false, hasName: false },
    dynamic: ({ hour }) => hour !== undefined && (hour >= 23 || hour < 2),
  },
  {
    text: ({ name }) => `${name} at the stroke of midnight`,
    mood: 'mysterious',
    static: { language: 'en', incognito: false, workMode: false, hasName: true },
    dynamic: ({ hour }) => hour !== undefined && (hour >= 23 || hour < 2),
  },
];
